---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - 'bin/**'
    - 'Rakefile'
    - 'tiny_hooks.gemspec'
  NewCops: enable
  EnabledByDefault: true
  TargetRubyVersion: 2.5

# Oneline comment is not valid so until it gets valid, we disable it
Bundler/GemComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Lint/ConstantResolution:
  Enabled: false

# `define_hook` is little too complex...
Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# `define_hook` is little too complex...
Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

# `define_hook` is little too complex...
Metrics/PerceivedComplexity:
  Max: 10

Security/Eval:
  Exclude:
    - 'test/**/*.rb'

Style/ClassVars:
  Enabled: false

Style/ConstantVisibility:
  Exclude:
    - 'lib/tiny_hooks/version.rb'

Style/Copyright:
  Enabled: false

# I know what I do :)
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

# There are so many cases we just want `if` expression!
Style/MissingElse:
  EnforcedStyle: case
